name: Build
on: 
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 */7 * *'

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        msystem: ['MINGW64','MINGW32','CLANG64','CLANGARM64']
        include:
          - msystem: MINGW64
            prefix: mingw-w64-x86_64
            runner: windows-2022
          - msystem: MINGW32
            prefix: mingw-w64-i686
            runner: windows-2022
          - msystem: CLANG64
            prefix: mingw-w64-clang-x86_64
            runner: windows-2022
          - msystem: CLANGARM64
            prefix: mingw-w64-clang-aarch64
            runner: windows-11-arm
    steps:
      - name: 设置git
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      
      - name: 检查
        uses: actions/checkout@v4

      - name: 克隆python存储库
        run: |
          git clone https://github.com/msys2-contrib/cpython-mingw.git --depth 1

      - name: 安装MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          release: ${{ matrix.msystem == 'CLANGARM64' }}
          update: true
          install: >-
            make
            binutils
            autoconf
            autoconf-archive
            automake-wrapper
            tar
            gzip
            ${{ matrix.prefix }}-toolchain
            ${{ matrix.prefix }}-expat
            ${{ matrix.prefix }}-bzip2
            ${{ matrix.prefix }}-libffi
            ${{ matrix.prefix }}-mpdecimal
            ${{ matrix.prefix }}-ncurses
            ${{ matrix.prefix }}-openssl
            ${{ matrix.prefix }}-sqlite3
            ${{ matrix.prefix }}-tcl
            ${{ matrix.prefix }}-tk
            ${{ matrix.prefix }}-zlib
            ${{ matrix.prefix }}-xz
            ${{ matrix.prefix }}-tzdata

      - name: 编译
        shell: msys2 {0}
        run: |
          cd cpython-mingw
          set -ex

          if [[ "${{ matrix.msystem }}" == CLANG* ]]; then
            export CC=clang
            export CXX=clang++
          fi
          autoreconf -vfi

          rm -Rf _build && mkdir _build && cd _build

          #../configure \
          #  --prefix=${MINGW_PREFIX} \
          #  --host=${MINGW_CHOST} \
          #  --build=${MINGW_CHOST} \
          #  --enable-shared \
          #  --with-system-expat \
          #  --with-system-libmpdec \
          #  --without-ensurepip \
          #  --with-static-libpython \
          #  --enable-loadable-sqlite-extensions \
          #  --with-tzpath=${MINGW_PREFIX}/share/zoneinfo \
          #  --with-lto=yes
          ../configure \
            --prefix=${MINGW_PREFIX} \
            --bindir=${MINGW_PREFIX} \
            --sbindir=${MINGW_PREFIX} \
            --docdir=${MINGW_PREFIX}/doc \
            --host=${MINGW_CHOST} \
            --build=${MINGW_CHOST} \
            --enable-shared \
            --without-ensurepip \
            --with-system-expat \
            --with-system-libmpdec \
            --with-lto=yes \
            --disable-test-modules \
            --with-nt-threads \
            --with-static-libpython \
            --enable-loadable-sqlite-extensions \
            CFLAGS="-O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -D_WIN32_WINNT=0x0600 -DWINVER=0x0600 -fno-unroll-loops" \
            LDFLAGS="-Wl,--strip-all"

          make -j8

      - name: 安装
        shell: msys2 {0}
        run: |
          cd cpython-mingw
          set -ex
          cd _build

          pkgdir=python_pkgdir

          make -j1 install DESTDIR="${pkgdir}"

          # Fix shebangs
          _pybasever=$(./python.exe -c "import sys; print(f'{sys.version_info[0]}.{sys.version_info[1]}');")
          for fscripts in 2to3 2to3-${_pybasever} idle3 idle${_pybasever} pydoc3 pydoc${_pybasever}; do
              sed -i "s|$(cygpath -w ${MINGW_PREFIX} | sed 's|\\|\\\\|g')/bin/python${_pybasever}.exe|/usr/bin/env python${_pybasever}.exe|g" "${pkgdir}${MINGW_PREFIX}"/bin/${fscripts}
          done
          sed -i "s|#!${MINGW_PREFIX}/bin/python${_pybasever}.exe|#!/usr/bin/env python${_pybasever}.exe|" "${pkgdir}${MINGW_PREFIX}"/lib/python${_pybasever}/config-${_pybasever}/python-config.py

          # Create version-less aliases
          cp "${pkgdir}${MINGW_PREFIX}"/bin/python3.exe "${pkgdir}${MINGW_PREFIX}"/bin/python.exe
          cp "${pkgdir}${MINGW_PREFIX}"/bin/python3w.exe "${pkgdir}${MINGW_PREFIX}"/bin/pythonw.exe
          cp "${pkgdir}${MINGW_PREFIX}"/bin/python3-config "${pkgdir}${MINGW_PREFIX}"/bin/python-config
          cp "${pkgdir}${MINGW_PREFIX}"/bin/idle3 "${pkgdir}${MINGW_PREFIX}"/bin/idle
          cp "${pkgdir}${MINGW_PREFIX}"/bin/pydoc3 "${pkgdir}${MINGW_PREFIX}"/bin/pydoc

          # copy to /
          cp -rf "${pkgdir}"/* /

      - name: 压缩构建产物
        if: always()
        shell: msys2 {0}
        run: |
          cd cpython-mingw
          cd _build
          tar -zcf python.tar.gz python_pkgdir/

      - name: 上传
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-${{ matrix.msystem }}
          path: cpython-mingw/_build/python.tar.gz

      - name: 获取仓库信息
        id: repo-info
        run: |
          DEFAULT_BRANCH=$(curl -s https://api.github.com/repos/msys2-contrib/cpython-mingw | jq -r .default_branch)
          echo "default_branch=$DEFAULT_BRANCH" >> $GITHUB_OUTPUT
          echo "commit_sha=$(git ls-remote https://github.com/msys2-contrib/cpython-mingw.git $DEFAULT_BRANCH | cut -f1)" >> $GITHUB_OUTPUT
          echo "build_date=$(date -u +'%Y%m%dT%H%M%SZ')" >> $GITHUB_OUTPUT

      - name: 创建 Release
        id: create-release  # 添加步骤ID
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build-${{ steps.repo-info.outputs.build_date }}
          name: "cpython-mingw ${{ steps.repo-info.outputs.default_branch }}@${{ steps.repo-info.outputs.commit_sha }} Time:${{ steps.repo-info.outputs.build_date }}"
          body: "Automated build triggered on ${{ steps.repo-info.outputs.build_date }}"
          prerelease: true
          draft: false
          fail_orphans: true

      - name: 上传到 Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:

          upload_url: ${{ steps.create-release.outputs.upload_url }}  # 使用步骤输出值
          asset_path: cpython-mingw/_build/python.tar.gz
          asset_name: "python-${{ matrix.msystem }}.tar.gz"
          asset_content_type: application/gzip

      - name: 清理旧 Release
        if: always()
        run: |
          # 保留最新的50个Release
          gh api repos/${{ github.repository }}/releases --paginate | \
          jq -r '.[] | .id' | \
          tail -n +51 | \
          xargs -I {} gh api repos/${{ github.repository }}/releases/{} -X DELETE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}